baseURL                = "https://abishekgoda.com"
title                  = "~abishek"
theme                  = "PaperMod"
paginate               = 10
enableInlineShortcodes = true
enableRobotsTXT        = true
buildDrafts            = false
buildFuture            = false
buildExpired           = false
pygmentsUseClasses     = true
enableEmoji            = true
googleAnalytics        = "G-8JYM04V3BG"

[minify]
disableXML             = false
minifyOutput           = true

[languages.en.taxonomies]
category               = "categories"
tag                    = "tags"
series                 = "series"

[[languages.en.menu.main]]
name = "Posts"
url = "posts"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 20

[[languages.en.menu.main]]
name = "Categories"
url = "categories/"
weight = 10

[[languages.en.menu.main]]
name = "Lisp"
url = "https://lisp.abishekgoda.com"


[outputs]
home                   = ["HTML", "RSS", "JSON"]

[params]
env                    = "production"
description            = "Abishek’s corner on the internet. Mostly rants, some bad jokes and even worser advice. But take a look"
author                 = "Abishek Goda"
defaultTheme           = "auto"
disableThemeToggle     = false
showShareButtons       = true
showReadingTime        = true
displayFullLangName    = false
ShowPostNavLinks       = true
ShowBreadCrumbs        = true
ShowCodeCopyButtons    = true
ShowRssButtonInSectionTermList = true
ShowToc                = false

[params.profileMode]
enabled                = true
#imageURL               = " "
imageTitle             = "~abishek"
imageWidth             = 120
imageHeight            = 120
[[params.profileMode.buttons]]
name                   = "Posts"
url                    = "/posts"
[[params.profileMode.buttons]]
name                   = "About"
url                    = "/about"

[[params.socialIcons]]
name                   = "Github"
url                    = "https://www.github.com/abishek"
[[params.socialIcons]]
name                   = "Twitter"
url                    = "https://www.twitter.com/abishekgoda"
[[params.socialIcons]]
name                   = "Linkedin"
url                    = "https://www.linkedin.com/in/abishek"

