alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: www.abishekgoda.com
  type: PRIMARY
  zone: abishekgoda.com
- domain: abishekgoda.com
  type: ALIAS
  zone: abishekgoda.com
name: abishekgoda-com-website
region: blr
static_sites:
- build_command: git submodule update --init --recursive && hugo -d public
  environment_slug: hugo
  github:
    branch: main
    deploy_on_push: true
    repo: abishek/website
  name: abishekgoda-com-website
  routes:
  - path: /
  source_dir: /
