#+TITLE: First Trip To Japan
#+DATE: 2024-12-29T08:00:13+08:00
#+DRAFT: nil
#+CATEGORIES[]: entrepreneurship
#+TAGS[]: entrepreneurship, life, japan, singapore
#+DESCRIPTION: I had an opportunity to visit Japan and participate in the Ramen Tech conference earlier this month. As I continue to have my fanboi moment, I decided to write up my learnings and my experiences. Japan is a wonderful country and does live up to the hype :-)

** Prelude
My grandfather was an incredibly disciplined man, a teetotaler and vegetarian. Traveling as a vegetarian is a painful thing. It still is, but it must have been worse in the 60s. And yet he travelled quite a bit in his day. One of his such trips was to Japan. I think it was Tokyo or Osaka, but I don't recollect too well now. There were a few stories of his that stuck with me: one was about how difficult it was to get decent food - if you were a vegetarian, they understood you to be a herbivore and usually only had raw fruits and vegetables. He didn't think it was discriminative - rather, they didn't cook anything without an element of fish or meat in it, so this was the only option. The other was about how punctual and polite people acutally were. Many of those stories ended up creating a desire to try and live in Japan for a couple of years. While I am not sure if I will do that yet, my trip to Japan was a fantastic opportunity to experience this wonderful place.

** Fukuoka
ACE Singapore had organized a trip to participate in Ramen Tech along with a couple of other mixer events with local startups in Fukuoka, Japan. Now, Fukuoka is not the name we hear around when we talk Japan. One cabbie - on my ride to get my visa for Japan - quipped that Fukuoka is the origin land for the Yakuza culture. Not that we had to worry about that, but he felt he needed to let me know that. I didn't fact check it - a cursory read through wikipedia seems to agree with that. I had a completely open mind to this trip. I was participating to see if there is a market for my work, understand first hand how things work in Japan, whether there was an option to move my startup to Japan, among others. And the trip would be a success if I had a smooth trip, met a few people and didn't sweat the stuff. That way, the trip was a massive success. I met quite a few people, I got my market validated and have a reasonable understanding of the opportunity and even know if I can move my startup to Japan. Talking to an investor would have been the perfect icing on the cake, but it wasn't even in my list anyway. I still walked away with a couple of potential connections, so that icing was delivered in some level.

But this post is not about the loot. This post is my admiration for a country that seemed to have impressed my grandfather. Perhaps his stories had primed me for this experience.

My first impression of Fukuoka was: a cute and a quaint town. Its a city, but it just felt like Coimbatore from the early 2000s. Bangalore would be apter, but Bangalore was never a small town for the time I've known. Coimbatore was a fantastic place. It probably still is, for a lot of people. The last time I went there, though, I was fully disenchanted. After my first trip to Coimbatore, if I had an option to move there, I might have taken it up!

Over the next few days, Fukuoka came around as not so quaint, after all. But it still is cute. I didn't go around Tokyo or Osaka, so I don't yet know if the cuteness is its charm or if its just how Japanese cities are. In the future trips (yes, I see a few), I'll check out the other cities as well and correct my opinions as needed :-)

Let me start from the beginning.

** Visa

Did you know that the Japanese visa cost me SGD 8? I am still surprised. They gave a multi-enty multi-year visa for S$8! The Visa application itself was pretty straightforward. I had missed a document, so I had to go back in the second half with additional proof. The process was still very simple. Of course, all the consulates and embassies in Singapore have that wonder Nassim road residence - which just by itself is a fantastic place to walk down. If you've been to Chennai (there isn't a lot of space like Nassim road in chennai), its like walking down Besant Nagar avenues or Boat club road in RA Puram (maybe I get the name wrong? its the one with the German consulate). I haven't been in either places in the last 5 years, so am not sure the charm is intact.

** Flights

I booked the flights in a rush. So I didn't think too much about it. I was going to cancel the flights and rebook differently. Then I learnt that I couldn't cancel them. Well, I could but I won't get back anything. So I chose to live with that choice. The actual problem with my booking is this: it was via Tokyo. And pretty tightly booked too.

When I searched for flights from Singapore to Fukuoka, I mostly got options via Korea or China. For some reason, Manila didn't show up in the list. And secondly, flights via Tokyo or via Osaka didn't list. I didn't quite know the geography of the place when I booked the tickets. I had heard a friend goto Narita when he was in high school/college. So I looked up flights to Narita and booked. Like I said, I fully intended to cancel them!

The problem with a flight to Narita is that, Narita is far outside Tokyo - much like the Bangalore or Hyderabad airports. Of course, you get a train ride but it will cost you an hour one-way. When I actually sat down to re-plan the trip - which is when I figured I couldn't get a refund for my choices - I figured I could have flown to Osaka instead, or at least flown to Haneda instead of Narita and actually had a chance to look around Tokyo. Secondly, the trip from Narita to Fukuoka is almost 6 hrs by train. And train costs the same or a bit more than a flight with  check-in luggage. I was originally considering a train ride but a good friend reminded me that I was a vegetarian and that I didn't know much Japanese and lastly, 6 hours is a frigging long time to sit by myself. That's true. Some of these things don't really hit us until we either experience them or someone reads them out loud for us. So I frantically added a flight to Fukuoka in the mix but since I was doing this late, all my options were taken and I ended up taking a late morning flight to Fukuoka.

Dear agoda, if you do get to read this - please consider this feature. Ask for my passport nationality and then give me the best flights I can still take without a tonne of visas. Just because I am in Singapore, you cannot assume I carry a Singapore passport. A good number of us are in an Indian passport and we need a lot of Visas to go around. This situation has improved a lot, but its far from getting on the first flight out for the most part. And do try to see if you can add connecting flights domestically. I guess the code share doesn't work that way today. But maybe that's a space for disruption. I often find that a direct flight to Bangalore is more expensive than a flight to Chennai and a second flight to Bangalore. Of course, I'll need to work out the connections. Why can't the travel sites actually work this out - you have the data, you know how the transfers work. Isn't this the kind of stuff that we want AI to be good at?

** Hotel and Food

I picked up a budget hotel - APA hotel Tenjinnishi. I later learnt that just means APA hotel in Tenjin west. Anyway, it was a fantastic pic in a quiet neighbourhood and walkable to all the places I needed to go. I wasn't quite sure what to expect off a budget hotel, especially because we've all seen videos of tiny, optimal spaces in Japan from so many tik-tok videos. Yes, the space seemed small but it was quite cozy and had everything I needed in the hotel including a usable work desk. The hotel restaurant timings didn't quite work for me, so I never got around to trying it. The checkin and chekout processes were smooth and mostly automatic.

Going from Singapore, though, I had trouble remembering how cold it actually is outside. On day 1, I wanted to get some food but it was quite late - about 9.30PM. I walked out in my shorts and tee. Hungry and cold is not a great combination :D. I found a egg sandwich in a convenience store nearby and managed to run back to the hotel. And it taught me to be a bit more aware of the outside temperatures!

I got very lucky with the food situation, though. I had looked up a whole bunch of vegan and Indian places all over Fukuoka prior to my trip. The one thing I had not thought through was how would I commute to these places to get my food and their opening hours. On day 02, though, I figured out that there was an Indian place under a km walk from my hotel. And it gets better - the chef actually learnt to cook Indian food from an erstwhile restaurant in Mylapore, Chennai. For me, this was a full circle moment. The restaurant had been in PS Sivasamy Salai - one of my absolute favourite places in Chennai. That place, for inexplicable reasons, is my universe for my absolute favorite comedy of all time - "Marraige made in Saloon" by Crazy Mohan. And that this chef had to learn from there of all places and had to open his restauant 600m from my hotel room in Fukuoka and that I should pick that exact hotel for my trip. Now, everytime I am going to Fukuoka, I'll have at least one meal in this place. For me, this is like pilgrimage and inexplicably so.

Did I tell you there is a convenience store at every turn in Fukuoka? Perhaps its a Japanese thing (or even an Asian thing). There is one in every block and they all have good food. I was always worried that being a vegetarian in a smaller city in Japan could be a difficult thing. And boy was I wrong :-). There is a lot of good food, even for vegetarians (and even discounting the Indian places).

** Moving about
For most part, I just walked around everywhere. Again, my initial research was bang on and every place I needed to be was under a km from my hotel. That said, it was a lovely time of the year to visit Fukuoka. It was not even warm even when the sun was bright out - which was mind bending. I am expecting to sweat but am actually very very comfortable. I eventually ended up walking all over the ward in the evenings, just to get a hang of the place. I love it so much that I would actually be ok to live there for a few years. This is very much against my usual ideas of living in busy places, though. Maybe its the weather.

I tried the local bus and train a couple of times. They were quite straightforward to use. In fact, the train systems are so well integrated with Apple wallet that I didn't need to even buy a paper ticket. I got it once, though, just for the experience. And the wallet works with the bus as well. I was a tad anxious about missing my stop so I kept following up with google maps. The buses have internal displays that keep you updated about the stops (in English too). Most people speak only Japanese, though. So it will be required to know the language to live there for a longer time. Trains weren't all that different from SG, but the lighting and interiors looked quite dated and had a antique and cozy feel to it.

I took the cab a couple of times, entirely avoidable given the connectivity. Cabs are generally more expensive. As an experience, though, it is a delight. The vehicles are spotless, cab drivers even more so. All of them seemed better dressed than I was and they all seemed to wear a white glove that they just purchased. I wonder how they keep a white glove that stainless. My experience with whites has been less than desirable (and am just a dirt magnet at times).

** In conclusion

I loved the trip, every bit of it. I recently learnt that I am not a very visual person. I hav verbose descriptions of situations and imagery in my head, but the images themselves are always lost - in the sense, I cannot draw them and I can only describe them in words which usually is less defined than an image. For some reason, though, the streets of Tenjinnishi are imprinted in my head. Close to two months after the trip, I still recall so many spaces and situations so vividly I am myself a bit surprised at this new found ability. Since then I have travelled to Perth and to Bangalore. While I like all those places, I don't see myself living in Perth or Bangalore. I'll probably have business in both those places. Perth does have a vibrant business ecosystem and Bangalore claims to be Si Valley of India. But I can see myself living in Fukuoka. That's really how much I loved that city. The last time this happened was for Singapore and am here now. So let's see what lays ahead for Japan :-)
