#+TITLE: Rest In Peace Manoj
#+DATE: 2023-08-21T15:25:57+08:00
#+PUBLISHDATE: 2023-08-21T15:25:57+08:00
#+DRAFT: nil
#+CATEGORIES[]: life
#+TAGS[]: life memory
#+DESCRIPTION: A friend of mine escaped our known realm of life. He wasn't nearly old enough, though. I cannot understand why he was in a hurry. 

Rest In Peace Manoj. I will miss you. I keep thinking I should have made some time to meet you - either here in Singapore or back home in Chennai.

I think we met in the second year. And I don't think we hit it off all that much, though. We became friends much later, though, if I recollect right. I knew you wanted to be a pilot back then. And
you were pursuing engineering just cause that was a requirement for your folks to allow you to take up flying full time. For something that was a hindrance in your path, you spent a lot of effort
studying the coursework. You were amongst the few I knew that had access to all the reference texts.

The shared interest that connected us both was the love of heavy metal music. I think we have been to every single metal concert in IITM back in the day - except maybe the one in my finishing year
when you were already a pilot. I remember chatting for over a hour when you had joined TVS. I was surprised to know TVS had their own flight (or chartered one, I can't know for sure). And I was even
more surprised to know that one could hire pilots like that. And I blabbed something about being a glorified ... and you finishing the sentence with *driver* :-) I was worried if I was being
disrespectful, but we both laughed it off. But a little from there, we fell apart. I guess life got in our way.

It is funny, though, how we connected back after so many years. I remember asking everyone I meet if they had any contact with you. Somehow it seemed like you vanished from the face of the earth.
And then magically you appeared into the whatsapp group. I am happy I reached out and we could speak a few times at least in the last couple of years.

Rest In Peace Captain. You will be remembered as the one that chased and reached your goals.
