#+TITLE: Notes to my 20 yr old Self
#+DATE: 2025-09-25T09:24:19+08:00
#+DRAFT: nil
#+CATEGORIES[]: life
#+TAGS[]: lessons life entrepreneurship
#+DESCRIPTION: I have read a lot of "what I wish I knew as a 20 year old" or "what I would tell myself if I meet my 20 year old self" content. This is my version of that.

* Two Thoughts
I just have two things to my 20 year old self - be honest and put yourself first. Simple, but not easy.

** Be Honest
Don't get this wrong - I am an honest person in that I will never try to cheat anyone of anything. Honesty, however, is much more than that. Most of us are honest to our society and to our community. A whole bunch of us are not honest with ourselves. And honesty is the single most important ingredient to success, in my opinion. If I have to be frank, this is a little confusing especially to those of us brought up in the 90s middle class India. Money was akin to evil and there were movies showing how all rich people were predominantly evil and how they were morally corrupt and the like. Today when I watch the movies again - apart from being appalled at what I watched growing up - I realize that a lot of the "evil" rich characters aren't that evil or morally bankrupt at all. They are just brutally honest. Their actions are brutally consistent with what they are trying to do. Being honest is taking decisions that are consistent with your belief system. And the untold truth in that statement is that your belief system is not driven by your society or your community. It is driven by your compass, your north star. If you don't have one, you aren't anywhere near succeeding. You can't arrive, if you don't know the destination. For a good number of us, myself included, the north star is setup by social conditioning and religious misinterpretation.

Oh, for the entrepreneurs reading this: most VCs can sniff out this honesty in you. That's why the question why you are doing what you are doing. If you are doing something consistent with your north star, your compass - the VC will see that in your energy. After all, that's their entire business. And they probably can never explain. As humans we try to rationalise a good number of our decisions - so they tell you that you are early or there is a thesis mismatch or some other such. The truth is that they don't believe you are being honest with yourself. And if you are not honest with yourself, you probably cannot see things through. Your truth shows up in your energy. Maybe you can fake it, then you are a scammer. But a good number of us cannot. We are honest or we are not. We need some help to see it, though. This is also why some ideas get funded why others with paying customers don't. You cannot rationalise it beyond a point - not at the early stages when you don't have enough data for rationality or logic.

Learn to be honest. Honest to a fault. And honest to your compass even if its at logger heads with your society/community. In fact, the disparity would mean you need to find a different society rather than fit in. Take decisions that are aligned with your internal compass and your north star. Everything else is keeping you stuck.

** Put Yourself First
We aren't taught to put ourselves first. Instead we are taught not to be greedy and not to be selfish. In a good number of ways, they are wrong. You need to be greedy to some extent and you need to be absolutely selfish to succeed. The only thing you shouldn't do is actively disadvantage or hurt another life, again in my opinion. Hunters are not bad people and they don't accumulate bad karma for hunting the animal they did. Just as a lion will not be punished for hunting you down either. The lion, in fact, is brutally honest with itself - it feels hungry and you are food. It hunts for its food which is the most honest step it can take - all emotions aside.  The lion does not think if it needs to save some for its family. It probably does but it eats its fill first. This is true of most animals. And it is true of humans too, but somehow this has become synonymous to greed or selfishness and then made "evil".

I didn't use to be this. As a high schooler, I was immensely selfish. I'd never do anything that hurts my time or energy in a way I don't want. I'd prioritise everything to suit my ideas and never quite account for anyone else. I wouldn't active inconvenience anyone else either. My belief was that - if I needed to help another person, I need to be in a stable place first. So until I get there, I am not going to be able to meaningfully help anyone. Somewhere in my adolescent years, I completely lost this skill. For the entire young adult years, I have spent prioritising every else in my life that's not me. Even today, as a parent, I do prioritize my kid over everything else. Is that wrong? No, but its not right either. The best thing I can do for my kid is be there when he needs me, not give him everything now. And for that, I need to prioritise my well being. I need get to my stable place first before I can pull him, my family, my friends or anyone else up. I need to go back to my beliefs.

So be selfish. Protect your time, your wealth, your well being and your future over everything else. Selflessness is a great virtue for a monk. And unless that's who you want to be, you are likely to be rewarded for your selfishness than for your selflessness. Society and community has its motivations, so don't fall for that. And like I mentioned earlier, when there is a mismatch, move to one where the mismatch is minimal.
