#+TITLE: Notes From Meditations 1/n
#+DATE: 2025-06-08T20:03:52+08:00
#+DRAFT: false
#+CATEGORIES[]: life meditations
#+TAGS[]: life meditations philosophy
#+DESCRIPTION: A pseudo intellectual collection of thoughts. The only good thing here is these are what I have arrived at on my own. Not necessarily original thoughts but they did occur to me organically. These are not lessons to take. Maybe you have better answers to these thoughts than I could. The dump doesn't mean I have stopped thinking about these. I don't think I ever will.

** Removed From Reality

I have never read the Gita fully. Nor have I read the Thirukkural fully. I’ve read them in parts and mostly understood them based on their English translations. And there start most of my problems. There is a fantastic quote I read someplace - Every written word is twice removed from reality: Some thing happens and you observe it. Now the observation in your recollection is already incorrect in that it doesn’t have the resolution of the actual incident (not that we are liars). Then we write it down. Now when you read it, it is further removed. What you understand from a piece of text is extremely embellished by your own experiences in life.

I do not listen to a lot of spiritual sermons. I sometimes listen to religious discourses but I often find them inconsistent, disconnected or just wrong. The only set of lectures that I have listened to more than anything else is that of JK. And he explicitly tells you why you shouldn’t be listening to him or be reading these texts. I am not going to find references for you, but you could take the chance and it might change your life. Or not. Why should it?

A whole lot of religious advise will tell you this: introspect and ask yourself. That is the best way to find the answers. The answers are not outside but they are all locked up inside you. I've never understood that, but I kind of believe it. As I grow older, I have realised that these are not answers to your physics question paper, your troubles with PDEs or even the bugs from the code we checked in last week. It could be, but its largely not that. The answers are often about things that are really important. But what is more important that those very things that will cost me my job, my degree or my thesis?

Precisely the problem. We are often incapable of understanding what is important. I am not above that either. I often wake up and recognize that the things I was so worried about or anxious about really didn’t matter. I topped my class in 10+2, but I came in second or third in 10. While it didn’t bother me as such, I did wonder if I was inadequate. When I joined uni, these two facts became irrelevant. I topped year 1 (along side Anand) in engineering shcool. By year 2, that was irrelevant. Somewhere in year 2, I decided I didn’t care about my grades. I continued to score well but I didn’t sweat a day from there on. I learnt a lot, on the other hand. I was consuming knowledge like my life depended on it. But most of that knowledge was data. I couldn’t process them. I just remember them. It took a few years after school for each of these data points to fall in place and “click” in my head. But I digress. Most of what I worried about didn’t matter at all in hindsight.

Does that mean I don’t worry these days? Not true. I still worry about a lot of things. But the realisation of futility happens a little earlier. The loop closes sooner than later.  So what stops me from learning that lesson? Introspection, or the lack of it. And being present in the moment.

** Living In the Moment

How many times have we all heard about “living in the moment”. I’ve never understood it. I’ve made my own share of jokes on it too. I still don’t fully get it. But you see, that is the problem. I am trying to get the meaning from external sources. I am looking to understand from other people who are living in the moment. But their communication when it reaches me is twice removed from their reality - which is not helping me. And it probably won't help you either. So what do you do? Meditate?

Meditation is over sold. I meditate - the way it is sold and my own way. You can sit in a place, close your eyes and hear yourself and write them down. If you do it long enough, you would create the next “Marcus Aurelius classic on Meditations”. Of course, it will clear your head. Once all the mundane things are out of your way, you experience clarity. And then you are able to introspect. Or that’s what I think will happen. I haven’t gotten that far. I enter clarity states in under 10 mins. But I don’t sustain them long enough to introspect. Longer meditations usually just have multiple such bouts. So I often find it sufficient to do a 15-20 min session every day. But the real meditation happens when you are immersed in your art. I am generously stealing from Seth Godin here.

When I am debugging something, when am writing up a plan, editing a document, even chatting with an AI -  I sometimes enter a flow state where the world around me ceases to exist. I don’t recognize time, bodily functions, environment or anything else. Nothing exists outside of my thought stream. And I often have wonderful insights and solutions to problems am not even actively trying to solve. Isn’t that wonderful? It would be, if I could do this reliably.

Living in the moment, then,  is mostly that. Living as though the world outside of you doesn’t exist. Absolute immersion in the task at hand. This will be sustainable if we are fundamentally healthy and take care of ourselves; self love - another factor that is very often overlooked. If we focus on the moment, do everything we can do with that moment then perhaps we can experience time transcience.  Once we transcend time, does anything really matter?

** What is Intelligence?

I read this somewhere and it just suddenly falls into place for me: the highest form of intelligence is the ability to observe without engaging. If you are able to observe the passing of time without engaging in it, you will attain your highest form of intelligence. Not sure what that would mean, though. Observing without judging is extremely hard. We are always judging - more so when we say we don’t. Why do we judge? Judging is our own insecurity. Do we judge a flower? I have never said - this flower will look great in a pink rather than the yellow it already is. But I have looked at some flowers and thought they were hideous. So I do judge a flower. We always judge fruits and vegetables - not for the pupose of buying them, but ugly fruit is a category on its own - tells more about us than the fruit. We judge animals - i hate pugs fwiw - and birds. But I don’t think any of these judge us. Are they not observing us? Maybe they are. But our presence is inconsequential to their existence until we pose a threat. So observing without judging is another form of living in the moment. If you are secure about yourself, you will not judge things around you. You will become secure only by introspection - only by adressing your fears. no, not in therapy. You have to face your fears internally and win them over. Perhaps that is the meaning of rebirth in Hindu mythology?

It takes an immense amount of patience to observe without engaging. We are often very reactive. We need to become inert in order to observe without judging - because a judgement is our reaction. So one way to address this is to not react. To not react, you need to be aware of the fact that you are reacting. Awareness, then, is the highst form of intelligence.

** Time is not real

I don’t like time. Almost no other animal cares. They recognize it perhaps. I very much doubt if they track it. Humans have created this construct to gain superiority over one another. Other than that, I don’t see the value that “time” adds to our life or our ability to do things. And if you are in a flow state and stop recognizing time, you are getting more done in less time - then you are basically disregarding time as a quantity. Besides, nothing stops because we don’t recognize time. Time waits for no man, but it is man that runs behind time as if it is the promised land.

If not for synchronising with the rest of the community, we really don't need to track time. Eat when you are hungry, sleep when you are asleep. Leave the intelligence to do what matters - intropsect and create rather than track time. Of course, that sounds like going back a few thousand years in time. Or not. I don't think we are even prepared to run this as a thought experiment. Perhaps, if UBI was ever implemented, we could actually experiment with this idea.

** Death

I've often wondered what I think about death. I am not the least bit scared of dying. I truly believe dying is like a cheat code. You stop playing by the rules, but that neither means you won nor you lost. You just exit. I often believed I wanted to live long. I want to see how things shape up in the later part of this century. More recently, though, I don't actually care. And in some ways, it is not a blessing to live all that long. I'd rather exit when am still at my best. Like Seinfeld quips: "when you hit that high note, say ‘good night’ and walk off.”

The important piece is to hit the 'high note'. The catch is, and being the machine learning guy that I am, to not get caught in a local maxima.

** Motivation

When you wake up in the morning, you need to look forward to the day. Or something like that. If you pursued something that you didn't enjoy, you would struggle to start your day.  I've almost never experienced this. Even on occasions where I clearly did not enjoy what I was doing. I experience this occasionally now. And yet, I have never been more interested or invested in what I do. Once you become an entrepreneur, you might have to lose all self doubt. There are times I am wondering if this is all worth it. And so I wonder if I did the right thing by going down this path. I've come too far to backtrack, so I have to cross the well or drown in it. Motivation is fickle. If you trust yourself sufficiently, if you have sufficient self confidence, motivation is not something you will ever need.

One of the things I learnt in yoga (again by introspection, not by lesson), is that to keep your balance, your core strength becomes somewhat vital. As stupid as it sounds, our core is vital to a lot of things. And that's where gut or instinct comes from. If we feel strong and confident, our decisions could seem to come from our gut. And maybe that is also why we get butterflies in our stomach when we are nervous. I guess people were all along trying to tell us the same thing: build your confidence and your core. Many other things will just fall in place. Or not. We can find out. If what we lose is just money and time, we haven't lost much. After all, we created both these constructs.
