#+TITLE: On the Power of Music
#+DATE: 2025-02-09T11:56:58+08:00
#+DRAFT: nil
#+CATEGORIES[]: nil nil
#+TAGS[]: nil nil
#+DESCRIPTION: I've never been much of a music fan. I listen to music but its not my goto for de-stressing, focusing or just relaxing. I often listen to music as an activity. Music, typically, occupies my attention. I tend to try to sing along, tap along - not quite dance along though - disrupting my thought trains and focus.

** The setup
Sid is learning to sing. And his choice of music is the Indian classical form, Carnatic music. Neither myself nor my wife understand or spend enough time listening to Carnatic music. Its not that we don't like it, it just never was a goto. After all, there is enough and some more of film music to fall back on for most of our purposes. Around the time my wife was pregnant with Sid, we started having a playlist of devotional songs in the morning. Again, we are not religious enough to do this. We both agreed that this kind of music might be a good way to start the day, especially given the number of things stressing us out back then. And around the time Sid was under a year old, we found a nice album from Chitti Babu ( a renowned veena player ) which was very interesting to listen to. And we noticed a pattern that Sid always responded positively to that album. He would generally be less cranky when this album was playing. To his credit, though, he was never that cranky anyway.

Even through his early childhood (1-2 years), he would specifically ask my wife to sing a few songs. He had a choice list, all carnatic and all melodic songs too. My wife, incidentally, does have a good singing voice. She isn't trained for one, nevertheless.We didn't take these too seriously, but it did strike us different that he enjoyed carnatic music - more so given our own sensibilities to the genre.

Around a year back, Sid told us that he wanted to formally learn to sing. We found a teacher near us and enrolled him. By this time, he was already learning to play the drums. We thought, he'd give it a month or two and perhaps he wouldn't like it as much. Boy were we wrong or what!? A year in, he just loves to sing. He'd be singing "sarali varisai" - patterned structures that are a building block of carnatic music all the time. Like when he's walking back from school and he'd be singing this. He'd be singing this in the shower. He truly enjoys singing. And am just super glad he does this.

I briefly tried learning music when I was 6 or 7 years old. I tried to learn because the teacher who came home to teach (yes, that was a thing back then), would give me beetel leaf. A bit of a taboo but hey, this was the 80s. I don't think anyone saw the problem in that. I managed 2 weeks (2-4 classes) and gave up. She'd try to make me sing the same two three things - maybe I was so terrible at it that she couldn't move past the first line? I guess everyone but my mom would agree with that :-)

** The stage
On sunday the 8th of Feb, Sid had a group competition in singing. And we more of less spent the majority of the day hanging around the venue, and a good portion of that inside the competition hall. There were so many pariticipants and so many kids bringing immense talent and energy to the room. It was honestly infectious to be there. Sid's group was amongst the last few participants, so we ended up listening to carnatic music (mostly good, but very energetic) for over 2-3 hours. And a few things happened. I noticed I wasn't bored at all. And I was bustling with ideas and making so many connections with my work. All the time, am listening to the kids singing. I didn't try to sing along ( I just don't believe I can even hold a candle to the talent in that room. ) and I was just enough distracted for my brain to get into overdrive. In fact, I wrote two LinkedIn posts in that 2-3 hours, a task that often takes 4-6 hours per post.

I've since tried to replicate it with lukewarm success. I haven't been able to get a 2-3 hour block to experiment with just so many things pulling me in all directions. The little experiments seemed to work out - although, recently I have been working in flow state for prolonged hours anyway. And this state is the best - you don't feel hungry, frustrated and just get so many things done in one stretch. It is terrible for my back but that's a completely different problem altogether. I will try to replicate this again and be a little more scientific in validating the idea. Maybe its just the energy and enthusiasm of a room full of kids singing.

By the way, Sid's group won a top 3 position in the competition.

** The reasoning
It is probably our tendency to explain our luck. We just cannot be happy that we are or that we got lucky. We just have to find a pattern for why that luck happened to us. I guess as adults, we are just taught to be disbelieving. Anyway, I have that tendency and I had to reason out why carnatic music, especially, did that magic on my ability to think and focus amidst distraction. I could've gotten lucky, but that wouldn't explain anything :-) .

I am a very mathsy person. I can understand a concept far better when it is communicated in math. Even if that math is beyond my capability. I won't be surprised if my memory is actually encoded in numbers much like our LLMs of today. And am not a visual person at all. It is fricking hard for me to conjure up images in my head. But I can draw them out if they are geometric. So abstract art is beyond me.

Carnatic music is extremely structured. You can easily encode them into numbers - the patterns and numerical symmetry are always staring at your face (or pouring into your ears ). Which would mean that these patterns are probably pre-existing pathways in my head - not for the music but for other things. They probably light up pathways that I don't otherwise exercise. Even during IIT days, I've noticed many students who sang Carnatic music. It is not so much that they were singers but they all sang when they were working or walking. It was almost autonomous - I don't think they even noticed their singing. So am somewhat inclined to think that there is more to my reasoning than I comprehend immediately.

** The conclusion
I am going to experiment this. I follow a bunch of singers that spend a lot of their "Kutchery" (performances) in exploring these structured patterns. I am curating a playlist of these. And one of these days, I should have a repeatable experiment to validate if Carnatic music really does all those wonders I think it did for me. The results are not that important, however. I already figured a few ways to enter flow states. But if there's another that I can reliably use, I'd love to have that in my toolkit.

Let's see if this experiment pans out. Interestingly, we are often playing western classical music (I prefer instrumental music, otherwise am always trying to sing along) in our google home. That doesn't seem to have the same effect as Carnatic music. If my experiment works, then there is another interesting line of thought to explore ;-)
