#+TITLE: Solopreneurship: Registration Woes
#+DATE: 2024-01-20T11:40:51+08:00
#+DRAFT: nil
#+CATEGORIES[]: entrepreneurship
#+TAGS[]: entrepreneurship, solopreneurship
#+DESCRIPTION: It is extremely hard for an NRI to setup a company in India. This post is part rant, part education.

I keep reading about how India is really moving up the ease of business list. That's nice to read but it doesn't seem to translate very well to common people like me, though. As a citizen of the country, it should be relatively simple for me to setup a company there. Even as a non-resident, it should be simple. Am non resident, but my passport is still Indian. So that is my home, irrespective of anything. I usually don't want to rethink this, but often times the way things work in India are so annoying, that I can't help but think if that's really my home.

I consulted an auditing firm to advice and help me through this process. While its mostly possible to do it myself, taking the help of an auditor makes it faster. Besides you'll anyway need to appoint an auditor as part of the process. The auditing firm, after listening to my plans adviced me to register an OPC - a One Person Company. They told me, and I looked up, it is possible to register an OPC as a non-resident Indian. This was because a "private limited" would bring a lot of regulatory paperwork which can be deferred to a point where we see real growth. Besides, I don't have partners in this game (at least, no one in India). Given these, OPC seemed like a god send solution.

It turns out, outside of the auditor, myself and the odd 1-2 websites, no one in India seems to be aware of the OPC provision for NRIs. Many other auditors were quite sure it is not possible. They argued about how it is not feasible to track how the NRIs run the office since they are not in the country anyway. Let us say this is true. Money laundering is a real problem. So governments and regulatory bodies have to take extra steps all the time. And am perfectly fine by that. My passport is Indian. I travel 2-3 times a year minimally. My parents live there too. Are we saying the governements have no way of knowing that? Besides, didn't all those people that cheated us out of few hundred crores start their companies within the country?

The nail in the coffin - the MCA website doesn't seem to be provisioned to support NRIs opening an OPC in India. Can we ever beat that? So my auditor suggests adding a local director to get past the MCA hurdle. And we did that. The local director would be onboard until the formalities are done and then resign. All the shares are held exclusively by me. After a 3 month back and forth, this was finally done on the 1st of January. I was elated - I thought, 2024 finally brings me good news. So I can now proceed and pick up pace...

Nope. You see, since the banks don't understand this NRI shareholding in OPC, I need to travel to Chennai to open the bank account. There were some top banks that wanted to see my office too. You see you need a space with a few computers to get the account. Even after COVID, they don't seem to know fully remote offices. You can't do e-KYC either. So its stuck in a limbo. The only way to move this along is to travel and get things done. I am not sure how am going to finish this step in the next few days though.

Now, I am beginning to wonder if things would have been easier if I just registered my company in Singapore. I am seriosuly considering this step now. Yes, it is going to be harder to meet the requirements but its likely to move along much faster and I might not need a second director either. So I have to make a call between registering something in Singapore or traveling to Chennai and completing the step there. I know entrepreneurship will bring challenges, but this is not what I imagined to become the problem.

Anyway, the educational note is this: if you want to register a company in India - esp as an NRI - just go with a private limited. Yes, the paperwork is difficult but its probably easier to set it up without having to travel back and forth. Or maybe hire a better auditor. I don't want to discuss that here, though. Its completely possible that my choice of auditor was just terrible at getting this done.

The burning questions in my head are these: how are so many startups getting setup in India? How are they able to deal with the MCA website issues? are there no remote-only companies in India? How am I not able to find the right set of resources to deal with this? Anyway, let me hope this moves one way or another. Wish me luck. I am probably going to need a lot of it.
